openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    Application for operations with contacts
tags:
  - name: Contacts
    description: Operations with contacts
  - name: Auth
    description: Operations with auth
servers:
  - url: <http://localhost:3000>
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
